spring.application.name=demo

#JPA SQL 로그 활성화
spring.jpa.show-sql=true

#JPA SQL 로그 출력 시 줄바꿈을 추가해 가독성을 높입니다.
spring.jpa.properties.hibernate.format_sql=true

#JPA SQL 로그 출력 시 SQL키워드에 색상 또는 스타일을 포함해 더 읽기 쉽게 출력합니다.
spring.jpa.properties.hibernate.hilight_sq;=true

#JPA SQL 로그 출력 시 매핑된 객체 정보 등을 주석 형태로 출력합니다.
spring.jpa.properties.hibernate.use_sql_comments=true
