spring.application.name=demo

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#jpa가 실행하는 sql출력
spring.jpa.show-sql=true

#sql을 보기좋게 정렬
spring.jpa.properties.hibernate.format_sql=true
