spring.application.name=demo

# data source
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=myuser
spring.datasource.password=mypass

## enable jdbc log
#logging.level.org.springframework.jdbc=DEBUG

#데이터베이스 연결을 최대 20개까지 생성해 애플리케이션이 동시에 20갸의 작업을 할 수 있록 설정
spring.datasource.hikari.maximum-pool-size=20

#애플리케이션이 데이터베이스 연동을 하지 않고 있는 때일지라도, 언제 갑자기 연동할지
#알 수 없으므로 일단 데이터베이스 연결을 최소 10개 유지하도록 설정
spring.datasource.hikari.minimum-idle=10

#HikariCP 로깅 레벨 설정
logging.level.com.zaxxer.hikari=DEBUG
