CREATE TABLE member (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    email VARCHAR(256) NOT NULL UNIQUE,
    age INTEGER
);

CREATE TABLE article (
   id BIGINT AUTO_INCREMENT PRIMARY KEY,
   title VARCHAR(256),
   description VARCHAR(4096),
   created TIMESTAMP,
   updated TIMESTAMP,
   member_id BIGINT,
   FOREIGN KEY(member_id) REFERENCES member(id) ON DELETE CASCADE
);


